export const ACTION_TYPES = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_BAG: "SET_BAG",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_SEARCH: "SET_SEARCH",
  ADD_PRODUCT: "ADD_PRODUCT",
};
